### ISSUE TITLE
Configurable fgrpc listen address

### ISSUE THREAD

**Issue by danehans** [fortio/fortio#113]
Similar to https://github.com/istio/fortio/issues/91 for fhttp, fgrpc needs a way to make it's listen address configurable.

**Comment by danehans** [comment]
It seems as though [requiring the host flag](https://github.com/istio/fortio/blob/master/pingsrv.go#L150-L155
) after `grpcping` would no longer be needed if we use `NormalizePort` and `setHostAndPort` to generate the `host` portion of the destination. This would be similar to what was done for generating the `urlHostPort` in fhttp.

**Comment by ldemailly** [comment]
there are 2 different things here

the client code and the server code

the client (like for http) takes the host:port (and http(s) url for http) as argument

the server uses flags to bind to a port (with the now new optional host)

**Comment by danehans** [comment]
@ldemailly It appears the client uses the server flag to construct the grpcping destination:

From https://github.com/istio/fortio/blob/master/pingsrv.go#L155:
```
dest := fmt.Sprintf("%s:%d", host, *grpcPortFlag)
```

If the client can ping any grpc destination, I would expect the destination not to use the `grpcPortFlag`.

**Comment by ldemailly** [comment]
You're right for the ping client but this task was more about `fortio load -grpc` 

Also I think the ping client in current code it's not quite right as you found:

So for that, the port flag should just be a default if not otherwise specified - ie the destination can be host:port like for grpc load and if only host is specified we can take the port from the flag like today
