### ISSUE TITLE
support http1 post / client side payload

### ISSUE THREAD

**Issue by ldemailly** [fortio/fortio#260]
We can already control server side reply size (size= parameter to echo server), and for GRPC load test pass a -payload string (though that's inconvenient for large payload/limited by the command line length)

We should support POST outside of GRPC

a) generated payload
b) raw file (which could be key/value pair encoded)

**Comment by olimpias** [comment]
Does h1 mean http 1.1/1.0 right?

**Comment by ldemailly** [comment]
yes vs h2 used in grpc

**Comment by olimpias** [comment]
May I work on this? Also shouldn't be there one more input flag for identifying content-type like json, xml.. etc right?

**Comment by ldemailly** [comment]
I was thinking to give it a shot, let's see if I manage to find the time this week otherwise sure

**Comment by alex-koturanov** [comment]
Looking forward to see HTTP POST support in Fortio to pass JSON data in the body of the request.

**Comment by olimpias** [comment]
Hi @ldemailly, if you are still busy, I can propose a solution and write my solution way to you for your confirmation before I start to implement.

**Comment by ldemailly** [comment]
Thanks, go ahead / give it a shot

**Comment by olimpias** [comment]
At the beginning, I was thinking to rename `Fetcher interface` because we were going to post a request, however the point our post again to fetch response(Not interested in input data or response details). So that I think  `Fetcher interface` and fetch method could be reused. Also I'm thinking that we can reuse flag payload for http as well, but we need to add raw type(json/xml) as a flag. For the request part, if a payload is set for http request, we could use POST method also set to content-type to header. I'm assuming that content-type will be set from raw type flag. Raw type will be mandatory for http payload. I mean if a user wants to use http payload, user has to add raw-type from flags as well . I would like to hear your opinions about my comment @ldemailly

**Comment by ldemailly** [comment]
I see 3 modes, 2 of which we have already for grpc: 

-payload-size random payload (though the content type is to be determined)
-payload string 
-payload-file -  for stdin or filename for a file to send as is - we do need content type option
