### ISSUE TITLE
gRPC|Unable to call gRPC service

### ISSUE THREAD

**Issue by ankitonedirect** [fortio/fortio#333]
I want to do  performance testing using this tool for that I am following below steps:

1) I have cloned this in my machine and able to open UI in browser
2) When I am trying to run using CLI it gives rpc error **NotFound desc = unknown service**

So here I am having few doubts:

1) If I want to call my service in gRPC server then how to call it?
2) If I want to pass multiple payload data ,how would I pass?

**Comment by ldemailly** [comment]
I'm not sure I fully understand your question, but:

Did you try the examples from https://github.com/fortio/fortio#grpc ?
(basically you need to run a server and a client, or a server and use it's web ui as (self) server)

you can change the payload data using one of:
```
  -payload string
        Payload string to send along
  -payload-file path
        File path to be use as payload (POST for http), replaces -payload when
set.
  -payload-size int
        Additional random payload size, replaces -payload when set > 0, must be
smaller than -maxpayloadsizekb. Setting this switches http to POST.
```
(from fortio -h  and details section of https://github.com/fortio/fortio#command-line-arguments )

**Comment by ldemailly** [comment]
going to close this but let me know and reopen if I didn't answer your question

**Comment by nmarjano** [comment]
I have followed the guide on : https://github.com/fortio/fortio

And I am running the fortio control UI and trying to kick of a grpc test from the GUI and i get the following error:

Aborting because of rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp: address localhost:8080/echo?delay=250us:30,5ms:5&status=503:0.5,429:1.5:80: too many colons in address"

Could you please provide me with some guidance?

**Comment by ldemailly** [comment]
I see you opened #506 for this and I answered there (that you need to use the right port number for grpc)

let me know there if that solves it and close that issue or keep it open with more info if it doesn't

thanks
