### ISSUE TITLE
Negative -1.0 qps printed in logs

### ISSUE THREAD

**Issue by ahmetb** [fortio/fortio#337]
see `-1.0 qps` at the end

```
$ fortio load  -qps 0 -n 1000 -c 1 [IP]

Fortio 1.3.1 running at 0 queries per second, 4->4 procs, for 1000 calls: [IP]
12:08:32 I httprunner.go:82> Starting http test for [IP] with 1 threads at -1.0 qps
```

is this normal?

**Comment by ldemailly** [comment]
Yes that’s how « max » qps, which you requested, is represented internally (normalized to -1 as you could ask in theory for a qps of 0.0000000001 which would otherwise display as 0)

I am on my phone right now but I am pretty sure the summary (not the log info) translates that back to « max » further down the output, no?

**Comment by ldemailly** [comment]
```
$ fortio load -qps 0 -n 4 http://www.google.com
Fortio 1.3.2-pre running at 0 queries per second, 4->4 procs, for 4 calls: http://www.google.com
16:39:51 I httprunner.go:82> Starting http test for http://www.google.com with 4 threads at -1.0 qps
Starting at max qps with 4 thread(s) [gomax 4] for exactly 4 calls (1 per thread + 0)
```
Notice the translation there ^ to **max**

I suppose the internal value could be hidden even in debug/info log but that would have other negative (ah!) effects
