### ISSUE TITLE
Large Payload Breaks UI

### ISSUE THREAD

**Issue by burkhartt** [fortio/fortio#461]
We are using the Fortio UI with 10326 characters (10 KB) of payload. When we press "Start" it seems to be doing a GET action, which seems to be exceeding the maximum browser limit for a querystring (I tested Chrome and Safari).

Has anyone seen this before and is there a recommended way around it?

**Comment by ldemailly** [comment]
Ah, yes, fortio UI uses GET so you can copy paste the URLs into test scripts to re trigger/tweak at leisure 

But indeed that doesn't work for large payloads (for which you could in the meantime use kubectl exec or the client directly)

need to figure out JS magic to switch for GET to POST depending on size of payload field

**Comment by ldemailly** [comment]
Also note the next thing you are likely to hit is having to set `-maxpayloadsizekb` and  `-httpbufferkb`

**Comment by ldemailly** [comment]
fixed in 1.14.2 (payload above 100 bytes will make the UI use a POST instead of GET)

please confirm, thanks!

**Comment by DanCNo** [comment]
Can confirm that this works. However, one thing I did come across was that if 
1. I execute the load test with a large payload and move onto the output page 
2. Press back on the browser to go back to the input form page to change a parameter of the load test
3. Change a parameter but don't do anything with the payload input box
4. Execute the load test again, it fails with the same error as before.
I assume the error occurs because the input page didn't register the change.

**Comment by ldemailly** [comment]
I miss a bunch of github notifications - will reopen as it seems using the back button doesn't run the checkPayload() function (yet fills up the form, yet resets the form type)
