### ISSUE TITLE
Please retire this repo and move the functionality into istio/istio

### ISSUE THREAD

**Issue by geeknoid** [fortio/fortio#49]
As discussed previously, can we move this from being a top-level repo to being a subdirectory in istio/istio? Perhaps istio/istio/tools/fortio for example?

Thanks.

@smawson @louiscryan @rshriram

**Comment by rshriram** [comment]
A. if its going under tools, we need simple names. like loadgen or something. No point in having pseudonyms for every tool.
B. From my recollection, this was used as a way to learn Go. I am unclear why this tool is needed as a key dependency in Istio, when we have so many load generators out there. Granted that this has more flexibility but it is by no means standard/widely used. People are much more likely to believe in istio benchmarks from neutral party tools like wrk/h2load, instead of benchmark from our own tool (gives the impression of bias).
C. If we need this purely for internal testing in CI/CD, then this should probably be part of the test suite under tests/ directory, and should not be used in any way to provide official Istio benchmarks.

**Comment by ldemailly** [comment]
Thanks for your input and thoughts. As discussed previously, the repo will stay as is for now, for the following reasons:

- it makes fortio "go get"able with a simple, short url `go get -u istio.io/fortio`
- it keeps the resulting image and binary minimal and without external dependencies (beside grpc)
- increased velocity and productivity:
  - it increases productivity - while istio/istio was in turmoil from mono repo and build changes,  I was able to make half a dozen major feature improvements and releases
  - istio/istio still doesn't have daily/weekly releases
  - shuffling fortio code around in the current state isn't an effective use of precious time

We can revisit later but for now this would not be a productive/useful change for the Performance WG

**Comment by geeknoid** [comment]
We need to discuss as a whole the policy regarding repos in our organization. If all the ACLs described in the community roles document were applied at this point, the creation of this repo would likely not have been allowed.

We need to have a discussion whether to grandfather this repo in or not.

**Comment by ldemailly** [comment]
@smawson approved the repo creation - feel free to discuss with him or submit an agenda item to the perf wg

also please don't use github issues here for that kind of discussion
